name: Build USRBG

on:
  schedule:
    - cron: '*/5 * * * *'
  repository_dispatch:
    types: [start-build-workflow]
  workflow_dispatch:

jobs:
  build:
    name: Build CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        
      - name: Install Dependencies
        run: npm i @actions/core mongodb fs-extra
        
      - name: Build USRBG
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        uses: ./
        id: build
        
      - name: Build CSS
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Build USRBG" || true
          git push
